### ISSUE TITLE
Can not access the keyword based documentation

### ISSUE THREAD

**Issue by NandaRam153** [peterservice-rnd/robotframework-rabbitmq#3]
Please, let me know how to access the keyword based documentation. So far Im not able to access it. The link provided only gives the code changes that was uploaded.
Greatly appreciated and Thanks.

**Comment by ailjushkin** [comment]
@NandaRam153 Hi, thanks for the issue, you are right, we have not set up a dynamic generation of the library documentation yet. 

As a workaround, you can download the html file https://raw.githubusercontent.com/peterservice-rnd/robotframework-rabbitmq/master/docs/RabbitMq.html to your desktop folder and open it locally.

To save it:

* Press CTRL + S.
* Choose desktop folder.
* Open the html file locally.

**Comment by ailjushkin** [comment]
@NandaRam153 Hi, now the documentation link is fixed.
