### ISSUE TITLE
Requirement robotframework==3.0.4 necessary?

### ISSUE THREAD

**Issue by banirsche** [peterservice-rnd/robotframework-rabbitmq#8]
Hi,

I just want to ask if the requirement robotframework==3.0.4 is really necessary?

Because when installing your library, it's downgrading my current robot framework installation and some new robot features won't work anymore...

**Comment by adsith-pv** [comment]
Hi, @banirsche 

I've been using it with the newest versions of RobotFramework and Pika for a while and everything seems to run fine.

**Comment by Snooz82** [comment]
@Lev-v ping. This change is super easy and we also run into this issue.
It works fine with 3.1.2 but it downgrades RobotFramework while installation...
